/**
 * dashboard-nav.ts — SINGLE SOURCE OF TRUTH for the parity-dashboard tab bar.
 *
 * Problem this solves: the tab bar was hand-copied into ~8 generators + static
 * template HTMLs (build-aggregate-index, build-event-diff, gate-report,
 * build-e2e-results.py, build-community-results.py, and the examples-sweep /
 * book-examples-sweep / fx-inspector template files). They drifted — a new tab
 * (event-diff) appeared on some pages and not others. The tab set is ONE
 * concern spanning N files; the boundary was wrong (CLAUDE.md domain-aligned
 * abstraction). Consolidated here.
 *
 * Mechanism: every page emits ONE placeholder `<nav class="tab-bar" id="topnav">`
 * + `<script src="nav.js">`. `nav.js` (generated from TABS below, written to
 * test_results/nav.js by build-aggregate-index.ts) renders the canonical tab
 * list and marks the active tab from `location.pathname`. A classic
 * `<script src>` loads on file:// (only fetch/XHR/modules are CORS-blocked
 * there), so this works whether the dashboard is opened from disk or served.
 *
 * To change the tabs: edit TABS here, run `npx tsx tools/build-aggregate-index.ts`
 * (rewrites nav.js). Every page — generated or static template — picks it up.
 */

export interface NavTab {
  href: string
  label: string
  count?: number
}

/** The canonical, ordered tab set. The ONLY place tabs are declared. */
export const TABS: NavTab[] = [
  { href: 'index.html', label: 'overview' },
  { href: 'examples-sweep.html', label: 'official', count: 34 },
  { href: 'book-examples-sweep.html', label: 'book', count: 18 },
  { href: 'e2e.html', label: 'e2e', count: 10 },
  { href: 'community.html', label: 'community + forum', count: 48 },
  { href: 'launch-gate.html', label: '🚦 launch gate' },
  { href: 'fx-inspector.html', label: 'fx a/b', count: 40 },
  { href: 'event-diff.html', label: 'event diff' },
]

const DEFAULT_META = 'desktop ↔ web parity'

/**
 * The HTML block every page embeds in place of a hand-written tab bar.
 * `meta` is the right-aligned caption (varies per page); it rides on a data
 * attribute so nav.js can render it without the tab list being duplicated.
 */
export function navBlock(meta: string = DEFAULT_META): string {
  const safe = String(meta).replace(/"/g, '&quot;')
  return `<nav class="tab-bar" id="topnav" data-meta="${safe}"></nav>\n<script src="nav.js"></script>`
}

// Self-contained tab-bar style injected by nav.js. element+class selectors
// (`nav.tab-bar a`) outrank each page's own `.tab-bar` rules, so every viewer —
// including gate-report.html which uses a different palette — gets an identical
// bar. No dependency on the host page's CSS vars.
const NAV_CSS = `nav.tab-bar{height:38px;display:flex;align-items:stretch;background:#1f2335;border-bottom:1px solid #2a2e46;padding:0 16px;gap:2px;box-sizing:border-box}
nav.tab-bar a{display:inline-flex;align-items:center;gap:6px;padding:0 14px;font-size:12px;color:#7a85b3;border-bottom:2px solid transparent;font-family:ui-monospace,Menlo,Consolas,monospace;text-transform:lowercase;letter-spacing:.04em;text-decoration:none;background:none;border-radius:0}
nav.tab-bar a:hover{color:#c0caf5}
nav.tab-bar a[data-active]{color:#ff1493;border-bottom-color:#ff1493;background:none}
nav.tab-bar .count{font-size:10px;background:#16161e;color:#565f89;padding:1px 6px;border-radius:8px}
nav.tab-bar .spacer{flex:1}
nav.tab-bar .meta{align-self:center;font-size:11px;color:#565f89;font-family:ui-monospace,Menlo,Consolas,monospace}`

/** The contents of test_results/nav.js — renders TABS into #topnav, active by path. */
export function navJs(): string {
  return `// AUTO-GENERATED by tools/lib/dashboard-nav.ts (via build-aggregate-index.ts).
// Single source of truth for the dashboard tab bar — edit TABS in
// tools/lib/dashboard-nav.ts, then re-run build-aggregate-index.ts. Do not edit.
(function () {
  var TABS = ${JSON.stringify(TABS)};
  var nav = document.getElementById('topnav') || document.querySelector('nav.tab-bar');
  if (!nav) return;
  // Inject a self-contained style once so the bar looks identical on every page.
  if (!document.getElementById('navjs-style')) {
    var st = document.createElement('style');
    st.id = 'navjs-style';
    st.textContent = ${JSON.stringify(NAV_CSS)};
    document.head.appendChild(st);
  }
  var cur = (location.pathname.split('/').pop() || 'index.html').toLowerCase();
  if (!cur) cur = 'index.html';
  var html = TABS.map(function (t) {
    var active = t.href.toLowerCase() === cur ? ' data-active' : '';
    var count = (t.count != null) ? ' <span class="count">' + t.count + '</span>' : '';
    return '<a href="' + t.href + '"' + active + '>' + t.label + count + '</a>';
  }).join('');
  var meta = nav.getAttribute('data-meta') || '${DEFAULT_META}';
  html += '<span class="spacer"></span><span class="meta">' + meta + '</span>';
  nav.className = 'tab-bar';
  nav.innerHTML = html;
})();
`
}
