import { describe, it, expect } from 'vitest'
import { TUTORIAL } from '../tutorialData'
import type { TutorialChapter } from '../tutorialData'

/**
 * T1 (#311, EPIC #309) done-when: ingest produces a complete TutorialChapter[]
 * for the T0-approved curated scope; assert chapter count + block integrity
 * for a sample chapter.
 *
 * tutorialData.ts is GENERATED by tools/ingest-tutorial.ts from the vendored
 * pinned-commit corpus. This test pins the contract T2 (#312) consumes.
 */
describe('tutorialData (T1 / #311)', () => {
  it('bakes exactly the curated 12 chapters, in order', () => {
    expect(TUTORIAL).toHaveLength(12)
    expect(TUTORIAL.map((c) => c.id)).toEqual([
      '01-welcome-to-sonic-pi',
      '01.2-exploring-the-interface',
      '02.1-your-first-beeps',
      '02.4-durations-with-envelopes',
      '03.1-triggering-samples',
      '04-randomisation',
      '05.2-iteration-and-loops',
      '06.1-adding-fx',
      '07.1-controlling-running-synths',
      '08.4-rings',
      '09.2-live-loops',
      '10.1-set-and-get',
    ])
  })

  it('every chapter has complete, well-formed metadata + blocks', () => {
    for (const c of TUTORIAL) {
      expect(c.id, c.id).toMatch(/^[\d.]+-[a-z0-9-]+$/)
      expect(c.section, c.id).toBeTruthy()
      expect(c.ordinal, c.id).toMatch(/^\d+(\.\d+)?$/)
      expect(c.title, c.id).toBeTruthy()
      expect(c.sourcePath, c.id).toBe(`etc/doc/tutorial/${matchSlug(c)}.md`)
      expect(c.blocks.length, c.id).toBeGreaterThan(0)
      for (const b of c.blocks) {
        if (b.kind === 'prose' || b.kind === 'web-note') {
          expect(b.html.trim(), `${c.id} prose`).toBeTruthy()
        } else if (b.kind === 'code') {
          expect(b.runnable, `${c.id} code`).toBe(true)
          // T1→T2 seam: T1 emits ONLY 'unverified'. T2 (#312) owns the
          // verified | engine-gap | web-adapted transitions.
          expect(b.status, `${c.id} ${b.id}`).toBe('unverified')
          expect(b.id, c.id).toMatch(/^[\d.]+-[a-z0-9-]+#\d+$/)
          expect(b.code.length, b.id).toBeGreaterThan(0)
        } else {
          expect(b.src, `${c.id} image`).toMatch(/^images\/tutorial\/.+\.(png|jpe?g|gif)$/)
          expect(typeof b.desktopOnly, `${c.id} image`).toBe('boolean')
        }
      }
    }
  })

  it('code-block ids are unique and stable (the address T2 validates)', () => {
    const ids = TUTORIAL.flatMap((c) =>
      c.blocks.filter((b) => b.kind === 'code').map((b) => (b as { id: string }).id),
    )
    expect(ids.length).toBeGreaterThan(0)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('sample chapter 02.1 "Your First Beeps" has expected structure', () => {
    const ch = TUTORIAL.find((c) => c.id === '02.1-your-first-beeps')!
    expect(ch.section).toBe('Synths')
    expect(ch.ordinal).toBe('2.1')
    expect(ch.title).toBe('Your First Beeps')
    const code = ch.blocks.filter((b) => b.kind === 'code')
    expect(code.length).toBeGreaterThanOrEqual(3)
    // First runnable block of the whole tutorial is `play 70` (grounded
    // against the pinned upstream source).
    expect((code[0] as { code: string }).code).toBe('play 70')
    // Heading must not swallow the following paragraph (regression: dropping
    // marked 'space' tokens collapsed block separators).
    const firstProse = ch.blocks.find((b) => b.kind === 'prose') as { html: string }
    expect(firstProse.html).toContain('<h1>Your First Beeps</h1>')
    expect(firstProse.html).not.toMatch(/<h1>Your First Beeps[^<]/)
  })

  it('GUI/interface screenshots are flagged desktopOnly; content diagrams are not', () => {
    const images = TUTORIAL.flatMap((c) =>
      c.blocks.filter((b) => b.kind === 'image'),
    ) as Array<{ src: string; desktopOnly: boolean }>
    const gui = images.find((i) => i.src.includes('GUI'))
    expect(gui?.desktopOnly).toBe(true)
    const envDiagram = images.find((i) => i.src.includes('env-'))
    expect(envDiagram?.desktopOnly).toBe(false)
  })
})

/** Recover the original mixed-case slug for sourcePath assertion. */
function matchSlug(c: TutorialChapter): string {
  const known: Record<string, string> = {
    '01-welcome-to-sonic-pi': '01-Welcome-to-Sonic-Pi',
    '01.2-exploring-the-interface': '01.2-Exploring-the-Interface',
    '02.1-your-first-beeps': '02.1-Your-First-Beeps',
    '02.4-durations-with-envelopes': '02.4-Durations-with-Envelopes',
    '03.1-triggering-samples': '03.1-Triggering-Samples',
    '04-randomisation': '04-Randomisation',
    '05.2-iteration-and-loops': '05.2-Iteration-and-Loops',
    '06.1-adding-fx': '06.1-Adding-FX',
    '07.1-controlling-running-synths': '07.1-Controlling-Running-Synths',
    '08.4-rings': '08.4-Rings',
    '09.2-live-loops': '09.2-Live-Loops',
    '10.1-set-and-get': '10.1-Set-and-Get',
  }
  return known[c.id]
}
